### ISSUE TITLE
Update text/content

### ISSUE THREAD

**Issue by jak-ing** [HackHPI/hackhpi.github.io#36]

**Comment by jak-ing** [comment]
There's a good list of specific topics under "Common Challenges" circling around the broad theme of "environment": http://www.un-documents.net/wced-ocf.htm Might be interesting to pick up some of these in our texts.

**Comment by FWirtz** [comment]
Also see: https://docs.google.com/document/d/1aFrgfm66Tjm4P8HkUa6R8jYT3dXqN0yEhNsqvk-ICVQ/edit#heading=h.war8uq9uv9kx

**Comment by jonaschn** [comment]
Intro text (For 24 hours of hacking,... ) doesn't fit to our FAQ explanation (Over a 1337-minutes period...)

**Comment by FWirtz** [comment]
@jonaschn We can kill the `1337` minute geek part imo

**Comment by jonashering** [comment]
Just worked a little on this: Now, FAQ should no longer contain references to health tech and references to raw data etc. are mostly replaced. Also, I changed the meta description.

@jak-ing @FWirtz, please proofread.

**Comment by FWirtz** [comment]
awesome work @jonashering, thanks! I just reviewed - looks very good!

**Comment by jonashering** [comment]
Lead text still talks about "massive data". Didn't come up with a good idea, but we should maybe change that, too, to avoid false expectations.

**Comment by FWirtz** [comment]
Agree, should fix that before merging.
