### ISSUE TITLE
Adapt lead text to match expectations

### ISSUE THREAD

**Issue by FWirtz** [HackHPI/hackhpi.github.io#47]
> Lead text still talks about "massive data". Didn't come up with a good idea, but we should maybe change that, too, to avoid false expectations.
https://github.com/HackHPI/hackhpi.github.io/issues/36#issuecomment-362657090

Didn't fix it with #43 as we couldn't think of an easy alternative but wanted to quickly merge the update anyways. Should probably fix it though, like @jonashering remarked.

## Respective paragraph
> Our planet is in trouble, no doubt. But we think that **by using the massive amount of data our world is producing** we can solve the biggest problems on earth: pollution, global warming and natural disasters. We want to provide a place for creative ideas which will make our blue planet a better place to live.

**Comment by jak-ing** [comment]
"But we think that technology and software bear the potential for solving..."
@jonashering @ma-ro ?

**Comment by FWirtz** [comment]
I like that, what do the others think?

**Comment by jonashering** [comment]
I like it, too!
