### ISSUE TITLE
Add WWF as Partner

### ISSUE THREAD

**Issue by FWirtz** [HackHPI/hackhpi.github.io#55]
We should prepare a branch and take a screenshot so we can speedup their approval.

**Comment by FWirtz** [comment]
Prepared as such:

![image](https://user-images.githubusercontent.com/6052785/39330864-34ea6e50-49a3-11e8-9c37-b8dfc33fbd3b.png)
---
![image](https://user-images.githubusercontent.com/6052785/39330990-9a27de1a-49a3-11e8-95fd-c900a7a925f7.png)
---
Do not merge yet, not approved by WWF so far.

CC @jak-ing @annkatrinkuessner

**Comment by FWirtz** [comment]
Description text taken from https://www.worldwildlife.org/about

**Comment by jak-ing** [comment]
Remove `<br>` which follows first line of description?

**Comment by FWirtz** [comment]
@jak-ing that's the way they have it on their website, so I thought I'll just copy that. Dunno. Unsure about the `<br>`... 🙈
