### ISSUE TITLE
Remove link to MLH website

### ISSUE THREAD

**Issue by FWirtz** [HackHPI/hackhpi.github.io#62]
The MLH homepage is still linked at the bottom of the page.
We want to remove that with the next release.
Not the Code of Conduct, just the link to their website.

**Comment by jak-ing** [comment]
Don't know. I think we still want the participants to adhere to their code of conduct as a guideline. However, we are once again not part of one of their "seasons" so same situation as in previous years. Maybe consult some upperclassmen about this?

**Comment by jak-ing** [comment]
![image](https://user-images.githubusercontent.com/15202881/38830992-5096193e-41be-11e8-879c-8bedb9c8b7ba.png)

**Comment by FWirtz** [comment]
@jak-ing I think we should keep a code of conduct, could easily change it so some other though.
Was referring to the link at the very bottom:
![image](https://user-images.githubusercontent.com/6052785/38860422-72690ab8-4230-11e8-9ef9-5266882d1b70.png)
second one

maybe https://hackcodeofconduct.org/ ?

**Comment by jak-ing** [comment]
But why then change it at all?

**Comment by FWirtz** [comment]
Well, the code of conduct is alright, but why are we linking to the MLH website? I don't see no use in doing so.

**Comment by jak-ing** [comment]
Ok, then let's remove the link from the bottom of the page and keep the one in the FAQ?

**Comment by FWirtz** [comment]
Sgtm!
