### ISSUE TITLE
Make P.E.T. Free visible and noticeable

### ISSUE THREAD

**Issue by lheilmann** [HackHPI/hackhpi.github.io#72]
Ich denke wir sollten sobald wie möglich auf der Website sichtbar machen, dass es sich um ein PET Free Event handelt. Im Scope dieses Issues meine ich textuell, so weit oben wie möglich.

**Comment by FWirtz** [comment]
IMO sollte das eher in die Vorab-Email an die Teilnehmer, denke das Logo in #71 und eine Erläuterung in der FAQ wie `What does PET Free mean? -> Our event is ...` sollten auf der Webseite ausreichen.

PET Free ist ein Teil von uns, aber meiner Meinung nach nicht so wichtig für den durchschnittlichen Besucher unserer Webseite, das gehört denke ich eher in die Vorab-Email.

(Siehe https://trello.com/c/jAc3hDyN/710-vorab-email-an-tn-schicken)

@jak-ing @jonashering Wie seht ihr das?
