### ISSUE TITLE
Update Live Page

### ISSUE THREAD

**Issue by FWirtz** [HackHPI/hackhpi.github.io#9]
- [x] update text for 2018
- [x] add current partners
- [x] add challenges?
- [x] add mentor info
- [x] ...
- [x] add Twilio code (see https://trello.com/c/bxeg9JCX/632-twilio-promocodes-anfragen)
- [ ] extend open data source

**Comment by FWirtz** [comment]
- [ ] get Codes from Twilio
- [ ] extend open data source

**Comment by lheilmann** [comment]
@FWirtz Please change the text of the workshop at 13:00 to: "Sustainability - an overview
